### ISSUE TITLE
Editar contatos

### ISSUE THREAD

**Issue by davidpvilaca** [douglasbolis/ntalk#1]
![captura de tela de 2015-02-02 16 44 44](https://cloud.githubusercontent.com/assets/9597125/6006593/e5061906-aafa-11e4-8b02-1f1977e0ca81.png)

Erro ao acessar o menu "Editar" na página dos detalhes do contato

**Comment by douglasbolis** [comment]
Problema no editar contato resolvido. Pode fazer o teste.
